# Site settings
title: 09443 Madrid
email: luis@09443.eu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.09443.eu" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
